version: '3'
services:
  airflow-webserver:
    image: apache/airflow:2.5.0
    container_name: airflow_webserver_project1
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    ports:
      - "8081:8080" # different port for each project
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: webserver
    depends_on:
      - airflow-scheduler

  airflow-scheduler:
    image: apache/airflow:2.5.0
    container_name: airflow_scheduler_project1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler
    depends_on:
      - airflow-init

  airflow-init:
    image: apache/airflow:2.5.0
    container_name: airflow_init_project1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: bash -c "airflow db upgrade"

  postgres:
    image: postgres:13
    container_name: postgres_project1
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

volumes:
  postgres_db_data:
